name: Tour Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java 11 Tour container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Start MongoDB for integration test
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.2
          mongodb-port: 12345

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=RubenBoone_AdvProg-Tour

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/advprog-tour:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/advprog-tour:latest